version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    working_dir: /app/frontend
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
    working_dir: /app/api
    ports:
      - "5000:5000"
    command: ["npm", "run", "dev"]
