# Base image for both frontend and backend
FROM node:14

# Install lsof
RUN apt-get update && apt-get install -y lsof

# Copy the entire project (both frontend and api directories)
COPY ./api /app/api
COPY ./frontend /app/frontend

# Set the working directory for the frontend and install dependencies
WORKDIR /app/frontend
RUN npm install

# Set the working directory for the backend and install dependencies
WORKDIR /app/api
RUN npm install

# Expose the ports for both the frontend and backend
EXPOSE 3000 5000
