version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.prod
    ports:
      - "5001:5001"
