# Base image for the backend
FROM node:16

# Set the working directory for the backend
WORKDIR /app

# Copy the API code
COPY . .

# Install dependencies
RUN npm install

# Copy .env file
COPY .env .env

# Expose the port the API runs on
EXPOSE 5001

# Start the API server
CMD ["npm", "run", "dev"]
